### ISSUE TITLE
Excluding jars

### ISSUE THREAD

**Issue by shuttj** [sbt/sbt-onejar#11]
Is there a way to exclude certain lib jars? For example, I don't want to include the scala-library.jar since I am using this in a java only project. Also, I have a library that is needed for compilation only and not at runtime.

**Comment by eric-aldinger** [comment]
I found this not to word because of the unmatched parenthesis in front of the old: var. Below works for excluding scoverage when it is added to plugins.sbt. 

'mappings in oneJar <<= (mappings in oneJar).map { depends: Seq[(File, String)] =>
  depends.filterNot(_._1.getName == "scalac-scoverage-runtime_2.11-1.2.0.jar") }`

For declared dependancies in your build sbt you can append  % "test" like protobuffs and ScalaTest below
`libraryDependencies` ++= Seq(
  "org.json4s" %% "json4s-native" % "3.4.1",
  "org.scalaj" %% "scalaj-http" % "2.3.0",
  "com.rabbitmq" % "amqp-client" % "3.6.5",
  "com.google.protobuf" % "protobuf-java" % "3.1.0" % "test",
  "org.scalatest" %% "scalatest" % "3.0.0" % "test")`
